### ISSUE TITLE
Failed to package for any platform (UE 5.3)

### ISSUE THREAD

**Issue by Shieldowskyy** [freezernick/ue-gjapi-core#188]
When packaging a project for the Windows platform, I get an error. It seems to be related to the upgrade of Unreal Engine to version 5.3. The most common error I see is 'Unknown structure' however I don't see any errors when compiling BPs.

Error: [pastebin](https://pastebin.com/mueGLx3w)
UE Version: 5.3.1

**Comment by freezernick** [comment]
Thanks for the report, I'll check this out ASAP.

Have you downloaded the plugin from GameJolt or from GitHub?
Which version are you using? (v1.1.6 or the v2.0 preview)

**Comment by Shieldowskyy** [comment]
Sorry for the late reply, I am using version v.1.1.6 of the plugin.

**Comment by freezernick** [comment]
Ah, so you've upgraded from 5.1 to 5.3 and the plugin was already installed at 5.1 ?
Then you'd have to download the 5.3 version from [here](https://github.com/freezernick/ue-gjapi-core/releases/download/v1.1.6/ue-gjapi-core-1.1.6-UE5.3.zip) and overwrite the old plugin files.

If you already did that, try selecting all nodes that are from the plugin, open their context menu and press "Refresh Node(s)". And then try packaging again.

I'm very sorry for the late reply ❤️
If the issue is still present, feel free to reopen this issue.
